### ISSUE TITLE
Catapult crashes

### ISSUE THREAD

**Issue by mancristiana** [rasmuskl/Catapult#4]
![image](https://user-images.githubusercontent.com/17469404/59830750-8f20eb00-9340-11e9-8d8a-d4c9818c6856.png)

**Comment by rasmuskl** [comment]
@mancristiana Can you check the logs in `%appdata%\Catapult\logs` for more information?

Also is it happening every time you run Catapult and activate it or when something specific happens?

**Comment by mancristiana** [comment]
@rasmuskl It happens every time I attempt to run Catapult. Here are the logs:

It might fail to index `c:\dev` ? I don't have that folder.
```
2019-06-21 09:00:34.474 +02:00 [Information] Started Catapult.
2019-06-21 09:00:34.790 +02:00 [Information] Registering hot key.
2019-06-21 09:00:34.792 +02:00 [Information] Starting delayed indexing of C:\Users\CristianaMan\AppData\Roaming\Microsoft\Windows\Start Menu, C:\ProgramData\Microsoft\Windows\Start Menu, C:\Users\CristianaMan\Favorites, C:\Users\CristianaMan\Desktop, C:\Users\CristianaMan\Documents, c:\dev
2019-06-21 09:00:34.815 +02:00 [Error] Delayed indexing failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Catapult.Core.Indexes.FileIndexStore.IndexDirectory(String path, HashSet`1 ignoredDirectories, ExtensionContainer extensionContainer)
   at Catapult.Core.Selecta.SearchResources.<>c.<EnqueueDelayedIndexing>b__10_0(Object o)
2019-06-21 09:00:34.949 +02:00 [Information] Unhandled exception (dispatcher).
2019-06-21 09:00:34.949 +02:00 [Error] Unhandled exception (dispatcher)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Catapult.Core.Indexes.FileIndexStore.GetIndexedPaths(String path)
   at Catapult.Core.Selecta.SearchResources.<>c.<BuildFileItems>b__11_0(String x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Catapult.Core.Selecta.SearchResources.BuildFileItems(String[] paths)
   at Catapult.Core.Selecta.SearchResources.GetFilesInternal()
   at Catapult.Core.Actions.ActionRegistry.<GetSearchFrame>b__8_1()
   at Catapult.Core.Actions.IndexableUpdateState..ctor(Func`1 fetchIndexables, Func`1 getUpdatedState)
   at Catapult.Core.Actions.ActionRegistry.GetSearchFrame(IIndexable[] indexables)
   at Catapult.App.MainViewModel.Reset()
   at Catapult.App.MainViewModel..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstance(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Catapult.App.MainWindow.InitializeComponent()
   at Catapult.App.MainWindow..ctor()
   at Catapult.App.App.ApplicationStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by rasmuskl** [comment]
@mancristiana I've released a version 0.2.5 with more error handling. Can you try that one and check the logs again? It should output which file fails.

Looks like you should be able to just start Catapult and it'll fetch the updated version.

Directories that don't exist don't fail :)

**Comment by mancristiana** [comment]
Here are the logs after installing the newest release: 
[logs.zip](https://github.com/rasmuskl/Catapult/files/3319599/logs.zip)

**Comment by rasmuskl** [comment]
@mancristiana Thanks! I've talked to the @danantal who's the main Catapult debuggifier / support wizard from Templafy.. He says he's happy to set up a debug session to figure out what's going on :)

**Comment by danantal** [comment]
We had a debug session and figured out that the problem was an invalid `index.json` file which made the deserialization fail and return null. Deleting it and it got recreated fixed the problem.. however I'm not sure how the invalid file could have been created...
I'll make a quick PR to handle that case :)

**Comment by rasmuskl** [comment]
@danantal @mancristiana Thanks for resolving the issue!
